include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "lib/l10n/generated/**"
    - build/**
    - android/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    prefer_single_quotes: true
